# Site settings
title: Dzakwan blog # site title
description: >- # site description
  He's writing in Bahasa about web technology and experience as a journal
  for documentation things that he learned, meet him <a href="https://github.com/dzakwanf" target="_blank" rel="noopener">@github</a>.
lang: en-US # default lang
timezone: Asia/Jakarta # set your timezone
image: /assets/img/icon.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/piharpi/jekyll-klise # site repo [optional]
mode: light # default theme "dark" | "light"

# Profile settings
author:
  name: M Dzakwan Falih # author name
  bio: >- # tell to the world
    "Hallo 🖐️, saya Dzakwan, seorang ahli teknologi informasi dengan fokus pada Linux, cloud security, dan DevOps. Di blog ini, saya berbagi pengetahuan dan pengalaman saya dalam membangun infrastruktur TI yang aman, andal, dan scalable dengan menggunakan teknologi terbaru dan praktik-praktik terbaik. Mari bergabung dalam perjalanan ini menuju keamanan dan keunggulan infrastruktur TI yang terbaik.
  username: dzakwanfalih # general username
  github: dzakwanf # github username
  twitter: dzakwanfalihh # twitter username
  facebook:  # facebook username
  email: zakwanfalih@gmail.com # email adress
  avatar: /assets/img/avatar.jpg # change with your own avatar

# URL settings
url: "https://dzakwanf.github.io" #
baseurl:
permalink: /:title/
google_analytics: # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
